### ISSUE TITLE
Char overflow corret

### ISSUE THREAD

**Issue by JBmiog** [JBmiog/QC-embedded#3]
Guys, we should still protect the chars for overflows! I'm adding this issue because else i might forget

**Comment by makis09917** [comment]
I also changed some stuff on the pc-terminal.c file in order for chars to go between -127 and 127 without "doing circles".
I don't know if there is a better way to do it. I will also upload this source file tomorrow.

**Comment by makis09917** [comment]
I just saw the new branch with the correction about the overflow. I ran the code, but it doesn't work properly. The check for the overflow should be within the kb_input_handler() function, because the values are created there for the keyboard. I will upload my implementation tomorrow which is more or less the same but in different part of the code

**Comment by makis09917** [comment]
Now that I think of it, there should be overflow check inside the kb_input_handler() (I have done it) and also when a packet is created (as done in overflow fix branch).

**Comment by JBmiog** [comment]
tested, working, good job!
